### ISSUE TITLE
Non-Class Usage not working in 2.5.3

### ISSUE THREAD

**Issue by Flosch1006** [ImpectAPI/impectPy#136]
### Description

Since the update to version 2.5.3 the old usage way (use the functions directly instead of using them as methods on the IMPECT class instance) stopped working.

### Steps to Reproduce

1. Install package using `pip install impectPy`
2. Run the following code:
```python
# load packages
import impectPy as ip
import os from dotenv
import load_dotenv 

# define login credentials
load_dotenv()
username = os.getenv("USERNAME")
password = os.getenv("PASSWORD") 

# get access
token token = ip.getAccessToken(username, password) 

# get iterations
iterations = ip.getIterations(token)
```

### Expected Behavior

The function should be executed without error.

### Actual Behavior

The following error is raised:
```python
AttributeError: 'Response' object has no attribute 'process_response'
```

### Environment

impectPy: 2.5.3
